import express from 'express';
import crypto from 'crypto';
import { query } from '../config/db.js';
import { authenticateToken, authorizeRole } from '../middleware/auth.js';

const router = express.Router();

/**
 * Generate API Key for service-to-service authentication
 * Only accessible by Owner, Manager, Head Branch Manager
 */
router.post('/generate', authenticateToken, authorizeRole('Owner', 'Manager', 'Head Branch Manager'), async (req, res) => {
  try {
    const { name, description, expires_at, scopes } = req.body;

    if (!name) {
      return res.status(400).json({
        success: false,
        message: 'API key name is required'
      });
    }

    // Generate secure API key
    const apiKey = `sk_${process.env.NODE_ENV === 'production' ? 'live' : 'test'}_${crypto.randomBytes(32).toString('hex')}`;
    const hashedKey = crypto.createHash('sha256').update(apiKey).digest('hex');

    // Store hashed version in database
    const result = await query(
      `INSERT INTO api_keys (
        user_id, 
        name, 
        description, 
        key_hash, 
        scopes,
        expires_at,
        created_by,
        created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, NOW())`,
      [
        req.user.id,
        name,
        description || null,
        hashedKey,
        scopes ? JSON.stringify(scopes) : JSON.stringify(['read:customers', 'write:customers']),
        expires_at || null, // null = never expires
        req.user.username
      ]
    );

    // Log security event
    console.log(`[SECURITY] API Key generated by ${req.user.username} (${req.user.role}) - Name: ${name}`);

    res.json({
      success: true,
      message: 'API key generated successfully',
      data: {
        api_key_id: result.insertId,
        name,
        // IMPORTANT: Only show key once - cannot be retrieved later
        api_key: apiKey,
        warning: 'Save this key securely. It will not be shown again.',
        scopes: scopes || ['read:customers', 'write:customers'],
        expires_at
      }
    });
  } catch (error) {
    console.error('Generate API key error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate API key',
      error: error.message
    });
  }
});

/**
 * List all API keys for current user
 */
router.get('/', authenticateToken, authorizeRole('Owner', 'Manager', 'Head Branch Manager'), async (req, res) => {
  try {
    const keys = await query(
      `SELECT 
        api_key_id,
        name,
        description,
        scopes,
        last_used_at,
        expires_at,
        is_active,
        created_at,
        created_by
      FROM api_keys 
      WHERE user_id = ? 
      ORDER BY created_at DESC`,
      [req.user.id]
    );

    // Parse JSON scopes
    const formattedKeys = keys.map(key => ({
      ...key,
      scopes: JSON.parse(key.scopes || '[]'),
      key_preview: '••••••••', // Never show actual key
      is_expired: key.expires_at ? new Date(key.expires_at) < new Date() : false
    }));

    res.json({
      success: true,
      data: formattedKeys
    });
  } catch (error) {
    console.error('List API keys error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve API keys',
      error: error.message
    });
  }
});

/**
 * Revoke API key
 */
router.delete('/:api_key_id', authenticateToken, authorizeRole('Owner', 'Manager', 'Head Branch Manager'), async (req, res) => {
  try {
    const { api_key_id } = req.params;

    // Verify ownership
    const keyCheck = await query(
      'SELECT api_key_id, name FROM api_keys WHERE api_key_id = ? AND user_id = ?',
      [api_key_id, req.user.id]
    );

    if (keyCheck.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'API key not found or access denied'
      });
    }

    // Soft delete (set inactive instead of actual delete for audit trail)
    await query(
      'UPDATE api_keys SET is_active = 0, revoked_at = NOW(), revoked_by = ? WHERE api_key_id = ?',
      [req.user.username, api_key_id]
    );

    console.log(`[SECURITY] API Key revoked by ${req.user.username} - ID: ${api_key_id}, Name: ${keyCheck[0].name}`);

    res.json({
      success: true,
      message: 'API key revoked successfully'
    });
  } catch (error) {
    console.error('Revoke API key error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to revoke API key',
      error: error.message
    });
  }
});

/**
 * Update API key (rename, update scopes, etc)
 */
router.put('/:api_key_id', authenticateToken, authorizeRole('Owner', 'Manager', 'Head Branch Manager'), async (req, res) => {
  try {
    const { api_key_id } = req.params;
    const { name, description, scopes } = req.body;

    // Verify ownership
    const keyCheck = await query(
      'SELECT api_key_id FROM api_keys WHERE api_key_id = ? AND user_id = ?',
      [api_key_id, req.user.id]
    );

    if (keyCheck.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'API key not found or access denied'
      });
    }

    const updates = [];
    const params = [];

    if (name) {
      updates.push('name = ?');
      params.push(name);
    }
    if (description !== undefined) {
      updates.push('description = ?');
      params.push(description);
    }
    if (scopes) {
      updates.push('scopes = ?');
      params.push(JSON.stringify(scopes));
    }

    if (updates.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'No fields to update'
      });
    }

    params.push(api_key_id);

    await query(
      `UPDATE api_keys SET ${updates.join(', ')}, updated_at = NOW() WHERE api_key_id = ?`,
      params
    );

    res.json({
      success: true,
      message: 'API key updated successfully'
    });
  } catch (error) {
    console.error('Update API key error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update API key',
      error: error.message
    });
  }
});

export default router;
